### ISSUE TITLE
test dependency sider/goodcheck is gone

### ISSUE THREAD

**Issue by Segaja** [ruby/typeprof#148]
While running the test for version 0.21.7 I ran into the issue that https://github.com/sider/goodcheck is gone. This makes https://github.com/ruby/typeprof/blob/v0.21.7/test/typeprof/goodcheck_test.rb unusable.

**Comment by ybiquitous** [comment]
@Segaja This issue seems to be fixed via 0c7af5341a6317c8c50da6163a3b472d5f307476.
