### ISSUE TITLE
Incorrect signature type with conditional implicit return

### ISSUE THREAD

**Issue by idrista** [ruby/typeprof#171]
While testing TypeProf, I tried different scenarios, and when using a one-line condition, I noticed that if there are 2 opposite one-line conditions, only the last one is taken in TypeProf's analysis.

# Implicit return:

```ruby
def demo(arg)
  {} if arg
  [] unless arg
end
```

TypeProf analyze `def demo: (untyped arg) -> Array[untyped]?`

# Explicit return:

```ruby
def demo2(arg)
  return {} if arg
  return [] unless arg
end
```

TypeProf analyze `def demo2: (untyped arg) -> ((Array[untyped] | Hash[untyped, untyped])?)`

Here are the scenarios in the playground:
https://mame.github.io/typeprof-playground/#rb=def+demo%28arg%29%0A++%7B%7D+if+arg%0A++%5B%5D+unless+arg%0Aend%0A%0Adef+demo2%28arg%29%0A++return+%7B%7D+if+arg%0A++return+%5B%5D+unless+arg%0Aend%0A%0A%0Adef+demo3%28arg%29%0A++arg+%3F+%7B%7D+%3A+%5B%5D%0Aend%0A%0Adef+demo4%28arg%29%0A++if+arg%0A++++%7B%7D%0A++else%0A++++%5B%5D%0A++end%0Aend&rbs=

**Comment by mame** [comment]
If I see correctly, this is the same semantics as actual Ruby does.

```ruby
def demo(arg)
  {} if arg
  [] unless arg
end

p demo(false) #=> []
p demo(true)  #=> nil
```

In Ruby, the evaluation results of statements other than the last one are not used. In this case, the return value of the statement `{} if arg` is discarded, and the method returns the result of `[] unless arg`, which is an empty array, or nil (when arg is true).

**Comment by idrista** [comment]
You're right, I got confused, there's nothing incorrect, my apologies

**Comment by mame** [comment]
Don't be sorry! Thank you for trying TypeProf!
