### ISSUE TITLE
Print "generated by TypeProf" in the head of output with timestamp

### ISSUE THREAD

**Issue by okuramasafumi** [ruby/typeprof#26]
It would be good to have something like "generated by TypeProf version 0.12.0 at 2021-01-04 00:53:00" in the head of output.
This is similar to what we have in RuboCop.
See: https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/formatter/disabled_config_formatter.rb

This might not be a good idea if generated output is designed to be edited by human after it's generated.

**Comment by mame** [comment]
Now it outputs `# TypeProf 0.11.0` by default. It can be suppressed by `--no-show-typeprof-version` option.

Memo: In general, there is a practice to avoid manual modification against an automatically-generated file. However, the result of TypeProf is supposed to be modified by hand, at least at this time. So, I'd like to avoid explicitly showing "generated by TypeProf", which discourges people to modify it too strongly. For the same reason, I avoided timestamp, and command-line options to generate the file. In future, I may change my mind.
