### ISSUE TITLE
typeprof stuck in rexml

### ISSUE THREAD

**Issue by alpaca-tc** [ruby/typeprof#261]
I ran typeprof with rexml and it stuck.
https://github.com/ruby/rexml [2f019f9](https://github.com/ruby/rexml/commit/2f019f9b33594b561e1ef39c42fab1f2fda51891)

It is not raising any errors, and probably the process is slow around `Vertex#show`.
Sorry I don't have more information as I don't have time.

I will check it later for more information on the problem.

**Comment by alpaca-tc** [comment]
I tested bundled gems with typeprof using [this script](https://gist.github.com/alpaca-tc/f76de2ee3ec3ec37830520a2a6ac09c1).
It reproduced hung of rexml.

**Comment by mame** [comment]
I have not tried the issue in rexml yet (sorry), but I fixed a similar infinite loop problem with #265. I'll try it later.

**Comment by alpaca-tc** [comment]
The problem still unfixed 👀

**Comment by alpaca-tc** [comment]
I just looked and it is fixed. Thanks for the fix 💛
