### ISSUE TITLE
Update VSCode extension repository link

### ISSUE THREAD

**Issue by maxveldink** [ruby/typeprof#70]
Currently, the repository linked on the Ruby TypeProf extension page is pointing to https://github.com/mame/vscode-typeprof. I believe the extension has completely been moved into this repo, so I think the updated link should be https://github.com/ruby/typeprof/tree/master/vscode or https://github.com/ruby/typeprof.

**Comment by mame** [comment]
Thank you very much! I have fixed package.json of the extension. It will be updated at the next release.
